### ISSUE TITLE
After use script

### ISSUE THREAD

**Issue by SebaBoler** [CutePoisonX/ffmpegInstaller#1]
Hello,

after when i run your script i have one problem. When i log to BubbleServer i have 
Video Transcoding supported:
no (ffmpeg has no libx264 support)

rest image and audio = "yes"

Its any possibility to solve this problem ??

(Synology 212j, 5.1 DSM )

**Comment by CutePoisonX** [comment]
Hi!

Just a few questions:
First of all, were there any warnings/errors during the installation? Did you enable libx264 support during the installation?
Did you try to convert a file with x264 codec in the command line with ffmpeg? If so, what was the outcome?
What output do you get if you simply type `ffmpeg` a terminal window?

Best regards

**Comment by SebaBoler** [comment]
Hello,

thank you very much for fast reply.
I didint have during the instalation any problem/errors. I press y when
script as about libx264.

Im not trying convert any file.

When i wrote ffmpeg its result below

ffmpeg: /lib/libz.so.1: no version information available (required by
/lib/libav            codec.so.55)
ffmpeg version 2.0.2 Copyright (c) 2000-2013 the FFmpeg developers
  built on Nov  6 2014 14:52:49 with gcc 4.6.4 (Linaro GCC branch-4.6.4.
Marvell             GCC Dev 201309-2126.3d181f66 64K MAXPAGESIZE ALIGN)
  configuration: --prefix=/usr/syno --incdir='${prefix}/include/ffmpeg'
--arch=a            rm --target-os=linux
--cross-prefix=/usr/local/arm-marvell-linux-gnueabi/bin/arm
 -marvell-linux-gnueabi- --enable-cross-compile --enable-optimizations
--enable-p            ic --enable-gpl --enable-shared --disable-static
--enable-version3 --enable-nonf            ree --enable-libfaac
--enable-encoders --enable-pthreads --disable-bzlib --disab
 le-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe
--disable-swsc            ale-alpha --disable-ffserver --disable-ffplay
--disable-devices --disable-bzlib             --disable-altivec
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable
 -libmp3lame --disable-decoder=amrnb --disable-encoder=zmbv
--disable-encoder=dca             --disable-encoder=ac3
--disable-encoder=ac3_fixed --disable-encoder=eac3 --disa
 ble-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd
--cc=/usr/local/
 arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
  libavutil      52. 38.100 / 52. 38.100
  libavcodec     55. 18.102 / 55. 18.102
  libavformat    55. 12.100 / 55. 12.100
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 79.101 /  3. 79.101
  libswscale      2.  3.100 /  2.  3.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  3.100 / 52.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options]
outfi            le}...

Use -h to get full help or, even better, run 'man ffmpeg'

[image: logo]
_Sebastian Pietrzak_

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.

2014-11-21 18:57 GMT+01:00 CutePoisonX notifications@github.com:

**Comment by CutePoisonX** [comment]
From your ffmpeg output, it is clear that the version you invoke is not the one that the script compiled for you. Please check if there is another version of ffmpeg in /opt/bin/ (type "/opt/bin/ffmpeg" into the terminal). If it says that it does not exist, something went wrong with the installation (does ipkg work?). Otherwise try to find an option in the bubbleupnp server to adjust the location of ffmpeg and change it to /opt/bin/ffmpeg (I don't know if such an option exists though). If this option does not exist, try to copy the ffmpeg installed in /opt/bin to /bin (rename the other one in advance).

If something doesn't work, post the output here.

Regards

**Comment by SebaBoler** [comment]
Folder /opt/bin/ffmpeg does not exists. Yesterday works, but now ipkg not
found ( need to find why ).

Ok now first i must return to moment when ipkg works, and after this repeat
install ffmpeg ??

[image: logo]
_Sebastian Pietrzak_

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.

2014-11-21 22:44 GMT+01:00 CutePoisonX notifications@github.com:

**Comment by CutePoisonX** [comment]
I see. That's most likely because you did not create a startscript for ipkg. Just google something like "ipkg start script" and you will find some solutions. Post back if you still have problems after ipkg is working again...

Best regards

**Comment by SebaBoler** [comment]
Hello again,

ok, my ipkg works good on DS212J. Next step its repeat run your script,
correct ??

[image: logo]
_Sebastian Pietrzak_

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.

2014-11-21 23:20 GMT+01:00 CutePoisonX notifications@github.com:

**Comment by CutePoisonX** [comment]
Hi! That's good to hear! I think you don't have to execute the script again,  what output do you get when you type "ffmpeg" (without any arguments) in the terminal?

**Comment by SebaBoler** [comment]
Result command ffmpeg below :

ffmpeg: /lib/libz.so.1: no version information available (required by
/lib/libavcodec.so.55)
ffmpeg version 2.0.2 Copyright (c) 2000-2013 the FFmpeg developers
  built on Nov  6 2014 14:52:49 with gcc 4.6.4 (Linaro GCC branch-4.6.4.
Marvell GCC Dev 201309-2126.3d181f66 64K MAXPAGESIZE ALIGN)
  configuration: --prefix=/usr/syno --incdir='${prefix}/include/ffmpeg'
--arch=arm --target-os=linux
--cross-prefix=/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-
--enable-cross-compile --enable-optimizations --enable-pic --enable-gpl
--enable-shared --disable-static --enable-version3 --enable-nonfree
--enable-libfaac --enable-encoders --enable-pthreads --disable-bzlib
--disable-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe
--disable-swscale-alpha --disable-ffserver --disable-ffplay
--disable-devices --disable-bzlib --disable-altivec
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame
--disable-decoder=amrnb --disable-encoder=zmbv --disable-encoder=dca
--disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3
--disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd
--cc=/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
  libavutil      52. 38.100 / 52. 38.100
  libavcodec     55. 18.102 / 55. 18.102
  libavformat    55. 12.100 / 55. 12.100
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 79.101 /  3. 79.101
  libswscale      2.  3.100 /  2.  3.100
  libswresample   0. 17.102 /  0. 17.102
  libpostproc    52.  3.100 / 52.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options]
outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

[image: logo]
_Sebastian Pietrzak_

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.

2014-11-28 0:01 GMT+01:00 CutePoisonX notifications@github.com:

**Comment by CutePoisonX** [comment]
Ok, this is still not the version that the script produces. Make sure that ffmpeg is in /opt/bin. If not, run the script again. If it is already there, try to add "/opt/bin:/opt/sbin" to the line which begins with PATH= in the files /etc/profile and /root/.profile so that the line looks like: "PATH=/opt/bin:/opt/sbin: ...". Then log out and log in again (restart is usually not necessary).

After these steps, post the output of "ffmpeg" again.
Best regards
