### ISSUE TITLE
DS216j support

### ISSUE THREAD

**Issue by bjornljungdahl** [CutePoisonX/ffmpegInstaller#10]
Hello,

I just bought a new Synology NAS, DS216j

It seems to be doing quite good, but it lacks MPEG transcoding capability. I record TV-programs into MPEG2 format and would like to stream to Chromecast.

Is there any plan to include support for DS216j ?

Best Regards // Björn Ljungdahl

**Comment by ghost** [comment]
Have you tried anything yet?

**Comment by bjornljungdahl** [comment]
No, I gave up.  I didn't get any comments or feed-back.
