### ISSUE TITLE
Multi-thread

### ISSUE THREAD

**Issue by ghost** [CutePoisonX/ffmpegInstaller#2]
Hello,

I have a DS214play and have installed ffmpeg with your script. But multi-thread is not enabled.
How can I enable this?

Frank

**Comment by CutePoisonX** [comment]
Hi! You're right, this is not enabled by default.
In order to enable it, you have to set the "--enable-pthreads" flag in the ffmpeg configuration I think.
So when the script asks you if you want to change ffmpegs configuration, choose yes, copy the original configuration and add "--enable-pthreads" (without parenthesis).
If it succeeds I will add it as a default, thanks for your notice on that and please report back!

Best regards

**Comment by ghost** [comment]
Thx CutePoisonX,

I installed it now with --enable-pthreads and --enable-libmp3lame; the installation finished without errors.
But if I run /opt/bin/ffmpeg it says: WARNING: library configuration mismatch (see picture)

![schermafdruk 2015-05-29 00 22 06](https://cloud.githubusercontent.com/assets/5961917/7872514/f5b43f14-0598-11e5-9acf-af05dc9a9708.png)

Is there a way I can fix that?
(/usr/syno/bin/ffmpeg does still exists as stock ffmpeg)

**Comment by CutePoisonX** [comment]
Looks like the listed libraries were not configured with "--enable-pthreads". Maybe it works nevertheless in your case, the warning does not list x264 for example.
However, this exceeds my ffmpeg-knowledge a little bit, would be great if you could do a little test conversion to check if it works properly, thanks!

**Comment by ghost** [comment]
It works but it says:
Warning: not compiled with thread support, using thread emulation

**Comment by CutePoisonX** [comment]
Hi! 
I've created a branch for this matter. I've changed the downloaded version to ffmpeg-mt, maybe this works!
Please try it again with: 
`git clone -b testing_multi_thread https://github.com/CutePoisonX/ffmpegInstaller`
and execute the script like usual (no need to provide --enable-pthreads).

**Comment by ghost** [comment]
I am trying it now. I will post back. (maybe tomorrow because I have to work)

**Comment by ghost** [comment]
Installation works fine.

if I want to add a subtitle to a video file gives me syntax errors (while the same syntax gives me no errors with 'normal' ffmpeg script).

I will use the normal ffmpeg script

**Comment by CutePoisonX** [comment]
Do I understand you correctly that the installation did work but when you executed ffmpeg, you got syntax errors? Could post the actual error message here - this would help me a lot debugging the error...
Thanks again.

**Comment by ghost** [comment]
The installation with your ffmpeg-mt script does install without error; but I still get the library mismatch error (see printscreen below)
![schermafdruk 2015-06-01 10 57 10](https://cloud.githubusercontent.com/assets/5961917/7909528/1fc8e032-084d-11e5-8297-8b31671f1ecc.png)

When I want to add a subtitle file to a video file it gives me the following error:
Unrecognized option 'fix_sub_duration'

I allways use the following syntax (as part of a script):
/opt/bin/ffmpeg -fflags +genpts -v 8 -fix_sub_duration -i "$dirName/$fileName" -sub_charenc UTF-8 -i "$dirName/${subtitleFileName[0]}" -vcodec copy -acodec copy -scodec srt -n "$dirName/$strippedFileName.muxed.mkv" 2> "$dirName/$strippedFileName.muxed.!sync" &

I removed the fix_sub_duration then it start complaining about -sub_charenc.

**Comment by ghost** [comment]
I used http://cytec.us/syno/test-spk/ffmpeg/ and it works.

SRC: https://github.com/SynoCommunity/spksrc/pull/1662

**Comment by CutePoisonX** [comment]
Great source! Thanks for pointing that out, didn't know that those existed ...
